[package]
name = "ast"
version = "0.1.0"
authors = ["Hawk Weisman <hi@hawkweisman.me>"]

[dependencies.seax_util]
git = "https://github.com/hawkw/seax_util.git"

[dependencies.seax_svm]
git = "https://github.com/jFransham/seax_svm.git"
